# Generated by Django 3.1.2 on 2020-10-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://toppng.com/uploads/preview/clipart-free-seaweed-clipart-draw-food-placeholder-11562968708qhzooxrjly.png', max_length=1500),
        ),
    ]
